/* Estado y utilidades */
const LS_KEY = 'cuentas_gr_data_v1';
let state = null;
function euros(n){ const v = (Math.round((n ?? 0) * 100)/100); return v.toLocaleString('es-ES',{style:'currency',currency:'EUR'}); }
function save(){ localStorage.setItem(LS_KEY, JSON.stringify(state)); }
function today(){ const d = new Date(); return d.toISOString().slice(0,10); }
function recalc(){ state.movimientos.sort((a,b)=> (a.fecha||'').localeCompare(b.fecha||'')); let saldo = Number(state.saldoInicial)||0; let e=0,s=0; for(const m of state.movimientos){ const c=Number(m.cantidad)||0; if((m.tipo||'').toLowerCase()==='entrada'){ e+=c; saldo+=c; } else { s+=c; saldo-=c; } m.saldo=saldo; } return {saldo, entradas:e, salidas:s}; }
function renderAll(){ fillCategorySelects(); document.getElementById('inp-saldo-inicial').value = state.saldoInicial ?? 0; const {saldo, entradas, salidas}=recalc(); document.getElementById('saldo-inicial').textContent=euros(state.saldoInicial||0); document.getElementById('total-entradas').textContent=euros(entradas); document.getElementById('total-salidas').textContent=euros(salidas); document.getElementById('saldo-actual').textContent=euros(saldo); renderResumenTabla(); renderMovimientosTabla(); renderListas(); }
function renderResumenTabla(){ const tbody=document.querySelector('#tabla-resumen tbody'); tbody.innerHTML=''; const fDesde=document.getElementById('f-desde').value; const fHasta=document.getElementById('f-hasta').value; const fTipo=document.getElementById('f-tipo').value; const fCat=document.getElementById('f-categoria').value; const rows=[]; for(const m of state.movimientos){ if(fTipo && m.tipo!==fTipo) continue; if(fCat && m.categoria!==fCat) continue; if(fDesde && (m.fecha||'')<fDesde) continue; if(fHasta && (m.fecha||'')>fHasta) continue; rows.push(m);} for(const m of rows){ const tr=document.createElement('tr'); tr.innerHTML = `<td>${m.fecha||''}</td><td>${m.tipo}</td><td>${m.categoria||''}</td><td>${m.descripcion||''}</td><td>${m.metodo||''}</td>`+`<td class='num'>${m.tipo==='Entrada'? euros(m.cantidad): ''}</td>`+`<td class='num'>${m.tipo==='Salida'? euros(m.cantidad): ''}</td>`+`<td class='num'>${euros(m.saldo||0)}</td>`+`<td><button data-del='${m.fecha}|${m.descripcion}|${m.cantidad}' class='btn-secondary'>🗑</button></td>`; tbody.appendChild(tr);} }
function renderMovimientosTabla(){ const tbody=document.querySelector('#tabla-mov tbody'); tbody.innerHTML=''; for(const m of state.movimientos){ const tr=document.createElement('tr'); tr.innerHTML = `<td>${m.fecha||''}</td><td>${m.tipo}</td><td>${m.categoria||''}</td><td>${m.descripcion||''}</td><td>${m.metodo||''}</td>`+`<td class='num'>${euros(m.cantidad||0)}</td>`+`<td><button data-del='${m.fecha}|${m.descripcion}|${m.cantidad}' class='btn-secondary'>🗑</button></td>`; tbody.appendChild(tr);} }
function fillCategorySelects(){ const selCat=document.getElementById('sel-categoria'); const fCat=document.getElementById('f-categoria'); const tipoSel=document.querySelector('select[name="tipo"]'); function update(){ const tipo=tipoSel.value; const cats = tipo==='Salida'? state.listas.gasto : state.listas.ingreso; selCat.innerHTML=cats.map(c=>`<option>${c}</option>`).join(''); } tipoSel.onchange=update; update(); const allCats=Array.from(new Set([...(state.listas.ingreso||[]),...(state.listas.gasto||[])])); fCat.innerHTML='<option value="">Todas</option>'+allCats.map(c=>`<option>${c}</option>`).join(''); const selMet=document.getElementById('sel-metodo'); selMet.innerHTML=(state.listas.metodos||[]).map(m=>`<option>${m}</option>`).join(''); }
for(const btn of document.querySelectorAll('.tabs button')){ btn.addEventListener('click', ()=>{ for(const b of document.querySelectorAll('.tabs button')) b.classList.remove('active'); btn.classList.add('active'); const tab=btn.dataset.tab; for(const s of document.querySelectorAll('.tab')) s.classList.remove('active'); document.getElementById('tab-'+tab).classList.add('active'); }); }
document.getElementById('btn-aplicar-filtros').onclick=renderResumenTabla; document.getElementById('btn-limpiar-filtros').onclick=()=>{ document.getElementById('f-desde').value=''; document.getElementById('f-hasta').value=''; document.getElementById('f-tipo').value=''; document.getElementById('f-categoria').value=''; renderResumenTabla(); }
const form=document.getElementById('form-nuevo'); form.addEventListener('submit',(e)=>{ e.preventDefault(); const fd=new FormData(form); const m={ fecha:fd.get('fecha')||today(), tipo:fd.get('tipo'), categoria:fd.get('categoria'), descripcion:fd.get('descripcion')||'', cantidad:Number(fd.get('cantidad')||0), metodo:fd.get('metodo')||'', nota:fd.get('nota')||'' }; state.movimientos.push(m); save(); renderAll(); form.reset(); });
function deleteMovementByKey(key){ const [f,d,c]=key.split('|'); const idx=state.movimientos.findIndex(m => (m.fecha||'')===f && (m.descripcion||'')===d && String(m.cantidad)===String(c)); if(idx>-1){ state.movimientos.splice(idx,1); save(); renderAll(); } }
for(const tbl of [document.getElementById('tabla-resumen'), document.getElementById('tabla-mov')]){ tbl.addEventListener('click',(e)=>{ const b=e.target.closest('button[data-del]'); if(b){ if(confirm('¿Eliminar este movimiento?')) deleteMovementByKey(b.dataset.del); } }); }
function renderListas(){ const ulIng=document.getElementById('ul-cat-ingreso'); const ulGas=document.getElementById('ul-cat-gasto'); const ulMet=document.getElementById('ul-metodos'); function renderUL(ul,arr,t){ ul.innerHTML=''; arr.forEach((txt,i)=>{ const li=document.createElement('li'); li.innerHTML=`<span>${txt}</span> <button data-x='${t}|${i}' class='btn-secondary'>x</button>`; ul.appendChild(li); }) } renderUL(ulIng, state.listas.ingreso||[],'ing'); renderUL(ulGas, state.listas.gasto||[],'gas'); renderUL(ulMet, state.listas.metodos||[],'met'); }
function addToList(arr,v){ v=(v||'').trim(); if(!v) return; if(arr.includes(v)) return; arr.push(v); save(); renderAll(); }
document.getElementById('btn-add-cat-ing').onclick=()=>{ addToList(state.listas.ingreso, document.getElementById('new-cat-ing').value); document.getElementById('new-cat-ing').value=''; }
document.getElementById('btn-add-cat-gas').onclick=()=>{ addToList(state.listas.gasto, document.getElementById('new-cat-gas').value); document.getElementById('new-cat-gas').value=''; }
document.getElementById('btn-add-metodo').onclick=()=>{ addToList(state.listas.metodos, document.getElementById('new-metodo').value); document.getElementById('new-metodo').value=''; }
for(const ul of [document.getElementById('ul-cat-ingreso'), document.getElementById('ul-cat-gasto'), document.getElementById('ul-metodos')]){ ul.addEventListener('click',(e)=>{ const btn=e.target.closest('button[data-x]'); if(btn){ const [t,i]=btn.dataset.x.split('|'); const idx=Number(i); if(t==='ing') state.listas.ingreso.splice(idx,1); if(t==='gas') state.listas.gasto.splice(idx,1); if(t==='met') state.listas.metodos.splice(idx,1); save(); renderAll(); } }); }
document.getElementById('btn-guardar-saldo').onclick=()=>{ const v=Number(document.getElementById('inp-saldo-inicial').value)||0; state.saldoInicial=v; save(); renderAll(); }
document.getElementById('btn-export-json').onclick=()=>{ const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='cuentas_gr_backup.json'; a.click(); }
document.getElementById('btn-export-csv').onclick=()=>{ const rows=[["Fecha","Tipo","Categoria","Descripcion","Metodo","Cantidad"]]; for(const m of state.movimientos){ rows.push([m.fecha,m.tipo,m.categoria,m.descripcion,m.metodo,String(m.cantidad).replace('.',',')]); } const csv=rows.map(r=>r.map(v=>`"${(v??'').toString().replace('"','"')}"`).join(';')).join('
'); const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='movimientos.csv'; a.click(); }
document.getElementById('btn-importar').onclick=()=>{ const f=document.getElementById('file-import').files[0]; if(!f) return alert('Selecciona un archivo JSON'); const reader=new FileReader(); reader.onload=()=>{ try{ const data=JSON.parse(reader.result); state=data; save(); renderAll(); }catch(e){ alert('Archivo no válido'); } }; reader.readAsText(f); }
document.getElementById('btn-restaurar').onclick=async()=>{ if(!confirm('¿Restaurar los datos iniciales? Se perderán los cambios no guardados.')) return; state=await loadInitial(); save(); renderAll(); }
window.addEventListener('load', init);

async function loadInitial(){ const res = await fetch('initial_data.json'); return await res.json(); }
async function init(){ const saved=localStorage.getItem(LS_KEY); if(saved) state=JSON.parse(saved); else state=await loadInitial(); save(); renderAll(); if('serviceWorker' in navigator){ try{ await navigator.serviceWorker.register('service-worker.js'); }catch(e){ console.warn('SW',e); } } }
